#https://www.serverless.com/examples/aws-node-simple-http-endpoint
#Install Serverless: https://www.npmjs.com/package/serverless
---
- name: Get Current Time from Lambda
  hosts: localhost
  gather_facts: no
  vars_files:
    - ./vars/lambda_vars.yml

  tasks:
 
    - name: Get Current Time from Lambda
      ansible.builtin.uri:
        url: "https://{{ url_prefix }}.execute-api.us-east-1.amazonaws.com/dev/ping"
      register: time_output

    - name: Print out the current time
      ansible.builtin.debug:
        var: time_output.json.message
