#https://www.serverless.com/examples/aws-node-simple-http-endpoint
#Install Serverless: https://www.npmjs.com/package/serverless
---
- name: Serverless: Programmatically Call Ansible Tower
  hosts: localhost
  gather_facts: no
  vars_files:
    - ./vars/lambda_vars.yml
    - ./vars/lambda_vault.yml

  tasks:

  - name: Serverless: Programmatically Call Ansible Tower
    ansible.builtin.uri:
      url: "{{ ansibletowerapitemplate_url }}"
      # headers:
        #   x-api-key:"{{ lambda_api_key }}"
